export interface IUser {
    userId:string;
    title:string;
    firstName:string;
    middleName:string;
    lastName:string;
    email:string;
    phone:string;
    nationality:string;
    dob:Date;
    gender:string;
    state:string;
    city:string;
    address1:string;
    address2:string;
    pinCode:string;
    photoFileName:string;
    employeeDetail:any;
}
